import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import PrimaryLinkButton from "~/component/PrimaryLinkButton";

function HeroBanner() {
  return (
    <section className="grid grid-cols-1 gap-12 my-12 sm:mt-24 px-8 sm:grid-cols-2">
      <div className="flex flex-col gap-4">
        <h1 className="text-4xl">Generate book covers with a click of a button</h1>
        <p className="text-1xl">
          Use AI to create a background for your book in seconds instead of a 
          designer and waiting for them to create one for you.
        </p>
        <PrimaryLinkButton href="/generate" className="self-start">
          Generate your Book Covers
        </PrimaryLinkButton>
      </div>

      <Image 
        src="/FloralFrameCover.jpeg" 
        alt="Floral Framed Book Cover"
        width="300"
        height="300"
        className="order-first justify-self-center sm:order-none"
      />
  </section>
  );
}

const HomePage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Book Cover Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center ">
        <HeroBanner />
      </main>
    </>
  );
};

export default HomePage;
